export const MASTRA_MODEL_PRO =
  process.env.MASTRA_MODEL_PRO || "google/gemini-3-pro-preview";

export const MASTRA_MODEL_FLASH =
  process.env.MASTRA_MODEL_FLASH || "google/gemini-3-flash-preview";

export const MASTRA_PLOT_MODEL = MASTRA_MODEL_PRO;

export const MASTRA_CHAPTER_MODEL = MASTRA_MODEL_FLASH;
export const MASTRA_PUZZLE_MODEL = MASTRA_MODEL_FLASH;
export const MASTRA_SLOT_FILLER_MODEL = MASTRA_MODEL_FLASH;
export const MASTRA_TOURISM_MODEL = MASTRA_MODEL_PRO;

export const MASTRA_SERIES_CONCEPT_MODEL = MASTRA_MODEL_PRO;
export const MASTRA_SERIES_CHARACTER_MODEL = MASTRA_MODEL_PRO;
export const MASTRA_SERIES_EPISODE_MODEL = MASTRA_MODEL_PRO;
export const MASTRA_SERIES_CONSISTENCY_MODEL = MASTRA_MODEL_FLASH;
export const MASTRA_SERIES_RUNTIME_EPISODE_MODEL = MASTRA_MODEL_PRO;
